#!/usr/bin/env bash
#
# Creates the two database roles and the application schema (DM-28, DM-32, DM-33, SECURITY.md SR-48).
#
# Why this is not a Flyway migration: the roles must exist before Flyway can connect for the first time. Something outside Flyway has to create them.
#
# Why this is a .sh and not a .sql: the Postgres entrypoint runs .sql files through psql with no variable substitution, so a .sql file could not read the passwords from the environment.
#
# Where it runs:
#   - locally, mounted into /docker-entrypoint-initdb.d/ (runs once, on an empty data directory)
#   - in CI, run explicitly against the service container, whose data directory is already set up
#
# It is idempotent, so running it a second time is harmless.

set -euo pipefail

: "${FT_MIGRATOR_PASSWORD:?FT_MIGRATOR_PASSWORD must be set}"
: "${FT_APP_PASSWORD:?FT_APP_PASSWORD must be set}"

psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  --set ON_ERROR_STOP=1 \
  --set migrator_password="$FT_MIGRATOR_PASSWORD" \
  --set app_password="$FT_APP_PASSWORD" \
  --set db_name="$POSTGRES_DB" <<'EOSQL'

-- ft_migrator owns the schema and has full DDL. Flyway connects as this role.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ft_migrator') THEN
        CREATE ROLE ft_migrator LOGIN;
    END IF;
END
$$;

-- ft_app has DML only: no DDL, no trigger control, no BYPASSRLS.
-- The application connects as this role.
-- This is what makes the DM-02 immutability triggers and the RLS policies real controls rather than strong suggestions — a role that can run ALTER TABLE can switch both off.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ft_app') THEN
        CREATE ROLE ft_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
    END IF;
END
$$;

ALTER ROLE ft_migrator PASSWORD :'migrator_password';
ALTER ROLE ft_app      PASSWORD :'app_password';

-- The application schema.
-- ft_migrator owns it, so every table Flyway creates is owned by ft_migrator too.
-- A table owner bypasses its own RLS policies, which is why migrations and seed data are unaffected by them while ft_app is fully subject to them.
CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION ft_migrator;

-- ft_app may use the schema but may not create anything in it.
GRANT USAGE ON SCHEMA app TO ft_app;

-- Every table ft_migrator creates in this schema from now on is readable and writable by ft_app.
-- Without this, each migration would have to remember its own GRANT statements.
-- Identity columns (GENERATED BY DEFAULT AS IDENTITY) need no separate sequence grant; INSERT on the table is enough.
-- The sequence grant below is only for a sequence created on its own.
ALTER DEFAULT PRIVILEGES FOR ROLE ft_migrator IN SCHEMA app
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ft_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ft_migrator IN SCHEMA app
    GRANT USAGE, SELECT ON SEQUENCES TO ft_app;

-- Nothing in this application uses the public schema.
REVOKE ALL ON SCHEMA public FROM PUBLIC;

-- Convenience for psql sessions.
-- The application sets currentSchema on the JDBC URL as well, so it does not depend on this.
ALTER ROLE ft_migrator IN DATABASE :"db_name" SET search_path = app;
ALTER ROLE ft_app      IN DATABASE :"db_name" SET search_path = app;

EOSQL

echo "01-roles-and-schema: created schema 'app', roles 'ft_migrator' and 'ft_app'"
