-- Base schema for DATA_MODEL.md §3-§9. Tables in parent-first order (DM-16). Triggers, RLS and seed data are V2-V4.

CREATE TABLE app.users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email           TEXT NOT NULL,
    display_name    TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT ux_users_email UNIQUE (email)
);

CREATE TABLE app.accounts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT NOT NULL,
    name            TEXT NOT NULL,
    type            TEXT NOT NULL,
    dedup_method    TEXT NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_accounts PRIMARY KEY (id),
    CONSTRAINT ux_accounts_user_id UNIQUE (user_id, id),
    CONSTRAINT ux_accounts_user_name UNIQUE (user_id, name),
    CONSTRAINT chk_accounts_type CHECK (type IN ('ASSET', 'LIABILITY', 'VIRTUAL')),
    CONSTRAINT chk_accounts_dedup_method CHECK (dedup_method IN ('ROW_FINGERPRINT', 'STATEMENT_BATCH', 'NONE')),
    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES app.users (id) ON DELETE RESTRICT
);

CREATE TABLE app.categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT NOT NULL,
    name            TEXT NOT NULL,
    kind            TEXT NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT ux_categories_user_id UNIQUE (user_id, id),
    -- Target of fk_transactions_category (DM-06): lets that FK check category kind in one step.
    CONSTRAINT ux_categories_user_id_kind UNIQUE (user_id, id, kind),
    CONSTRAINT ux_categories_user_name UNIQUE (user_id, name),
    CONSTRAINT chk_categories_kind CHECK (kind IN ('EXPENSE', 'INCOME')),
    CONSTRAINT fk_categories_user FOREIGN KEY (user_id) REFERENCES app.users (id) ON DELETE RESTRICT
);

CREATE TABLE app.category_rules (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id              BIGINT NOT NULL,
    account_id           BIGINT,
    narration_pattern    TEXT NOT NULL,
    category_id          BIGINT NOT NULL,
    priority             INT NOT NULL,
    is_active            BOOLEAN NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_category_rules PRIMARY KEY (id),
    CONSTRAINT ux_category_rules_user_id UNIQUE (user_id, id),
    CONSTRAINT chk_category_rules_pattern_length CHECK (char_length(narration_pattern) BETWEEN 2 AND 100),
    CONSTRAINT fk_category_rules_user FOREIGN KEY (user_id) REFERENCES app.users (id) ON DELETE RESTRICT,
    -- account_id NULL means every account; MATCH SIMPLE (Postgres default) then skips this check.
    CONSTRAINT fk_category_rules_account FOREIGN KEY (user_id, account_id) REFERENCES app.accounts (user_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_category_rules_category FOREIGN KEY (user_id, category_id) REFERENCES app.categories (user_id, id) ON DELETE RESTRICT
);

CREATE TABLE app.statement_imports (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id            BIGINT NOT NULL,
    account_id         BIGINT NOT NULL,
    source_filename    TEXT NOT NULL,
    file_sha256        TEXT NOT NULL,
    statement_date     DATE,
    period_start       DATE,
    period_end         DATE,
    status             TEXT NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    committed_at       TIMESTAMPTZ,

    CONSTRAINT pk_statement_imports PRIMARY KEY (id),
    CONSTRAINT ux_statement_imports_user_id UNIQUE (user_id, id),
    CONSTRAINT chk_statement_imports_status CHECK (status IN ('HELD', 'COMMITTED', 'REPLACED')),
    CONSTRAINT fk_statement_imports_user FOREIGN KEY (user_id) REFERENCES app.users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_statement_imports_account FOREIGN KEY (user_id, account_id) REFERENCES app.accounts (user_id, id) ON DELETE RESTRICT
);

-- related_transaction_id's FK is added after app.transactions exists, further down: the two
-- tables reference each other, so one side of the cycle has to come later.
CREATE TABLE app.statement_import_rows (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id                  BIGINT NOT NULL,
    statement_import_id      BIGINT NOT NULL,
    row_number               INT NOT NULL,
    raw_cells                JSONB NOT NULL,
    row_status               TEXT,
    related_transaction_id   BIGINT,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_statement_import_rows PRIMARY KEY (id),
    CONSTRAINT ux_import_rows_user_id UNIQUE (user_id, id),
    CONSTRAINT ux_import_rows_import_row_number UNIQUE (statement_import_id, row_number),
    CONSTRAINT chk_import_rows_row_status CHECK (row_status IS NULL OR row_status IN ('NEW', 'DUPLICATE', 'NEEDS_REVIEW')),
    CONSTRAINT fk_import_rows_user FOREIGN KEY (user_id) REFERENCES app.users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_import_rows_statement_import FOREIGN KEY (user_id, statement_import_id) REFERENCES app.statement_imports (user_id, id) ON DELETE RESTRICT
);

CREATE TABLE app.transactions (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id                    BIGINT NOT NULL,
    account_id                 BIGINT NOT NULL,
    txn_date                   DATE NOT NULL,
    txn_time                   TIME,
    amount_paise               BIGINT NOT NULL,
    narration                  TEXT,
    narration_normalized       TEXT,
    balance_after_paise        BIGINT,
    source                     TEXT NOT NULL,
    statement_import_id        BIGINT,
    source_row_id              BIGINT,
    source_row_fingerprint     TEXT,
    fingerprint_version        SMALLINT,

    transaction_type           TEXT NOT NULL DEFAULT 'UNCLASSIFIED',
    category_id                BIGINT,
    category_source            TEXT,
    category_rule_id           BIGINT,
    needs_wants                TEXT,
    notes                      TEXT,

    created_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_transactions PRIMARY KEY (id),
    CONSTRAINT ux_transactions_user_id UNIQUE (user_id, id),

    CONSTRAINT chk_transactions_amount_nonzero CHECK (amount_paise <> 0),
    CONSTRAINT chk_transactions_source CHECK (source IN ('IMPORTED', 'MANUAL', 'OFF_STATEMENT')),
    CONSTRAINT chk_transactions_type CHECK (transaction_type IN ('EXPENSE', 'INCOME', 'TRANSFER', 'UNCLASSIFIED')),
    CONSTRAINT chk_transactions_category_source CHECK (category_source IS NULL OR category_source IN ('RULE', 'MANUAL')),
    CONSTRAINT chk_transactions_needs_wants_values CHECK (needs_wants IS NULL OR needs_wants IN ('NEED', 'WANT')),
    CONSTRAINT chk_imported_has_source CHECK (
        source <> 'IMPORTED'
        OR (statement_import_id IS NOT NULL AND source_row_id IS NOT NULL AND narration IS NOT NULL)
    ),
    CONSTRAINT chk_non_imported_has_no_source CHECK (
        source = 'IMPORTED'
        OR (
            statement_import_id IS NULL
            AND source_row_id IS NULL
            AND source_row_fingerprint IS NULL
            AND fingerprint_version IS NULL
            AND narration_normalized IS NULL
            AND balance_after_paise IS NULL
        )
    ),
    CONSTRAINT chk_fingerprint_versioned CHECK ((source_row_fingerprint IS NULL) = (fingerprint_version IS NULL)),
    CONSTRAINT chk_needs_wants_expense_only CHECK (needs_wants IS NULL OR transaction_type = 'EXPENSE'),
    CONSTRAINT chk_category_source_paired CHECK (
        (category_source IS NULL) = (category_id IS NULL)
        AND (category_rule_id IS NULL OR category_source = 'RULE')
    ),

    CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES app.users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_transactions_account FOREIGN KEY (user_id, account_id) REFERENCES app.accounts (user_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_transactions_statement_import FOREIGN KEY (user_id, statement_import_id) REFERENCES app.statement_imports (user_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_transactions_source_row FOREIGN KEY (user_id, source_row_id) REFERENCES app.statement_import_rows (user_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_transactions_category_rule FOREIGN KEY (user_id, category_rule_id) REFERENCES app.category_rules (user_id, id) ON DELETE RESTRICT,
    -- MATCH SIMPLE skips this check when category_id IS NULL, which is how a TRANSFER or
    -- UNCLASSIFIED row (no category has that kind) is allowed to carry none (DM-06).
    CONSTRAINT fk_transactions_category FOREIGN KEY (user_id, category_id, transaction_type) REFERENCES app.categories (user_id, id, kind) ON DELETE RESTRICT
);

ALTER TABLE app.statement_import_rows
    ADD CONSTRAINT fk_import_rows_related_transaction
    FOREIGN KEY (user_id, related_transaction_id) REFERENCES app.transactions (user_id, id) ON DELETE SET NULL;

CREATE INDEX ix_import_rows_related_transaction
    ON app.statement_import_rows (user_id, related_transaction_id)
    WHERE related_transaction_id IS NOT NULL;

-- D-20 dedup backstop: bank rows keyed by content.
CREATE UNIQUE INDEX ux_transactions_fingerprint
    ON app.transactions (source_row_fingerprint)
    WHERE source_row_fingerprint IS NOT NULL;

-- §6.2: one raw row can produce at most one transaction.
CREATE UNIQUE INDEX ux_transactions_source_row_id
    ON app.transactions (source_row_id)
    WHERE source_row_id IS NOT NULL;

CREATE TABLE app.transaction_links (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id                   BIGINT NOT NULL,
    link_type                 TEXT NOT NULL,
    counterparty_account_id   BIGINT,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_transaction_links PRIMARY KEY (id),
    CONSTRAINT ux_transaction_links_user_id UNIQUE (user_id, id),
    CONSTRAINT chk_transaction_links_type CHECK (link_type IN ('TRANSFER', 'REIMBURSEMENT')),
    CONSTRAINT chk_transaction_links_counterparty CHECK (link_type = 'TRANSFER' OR counterparty_account_id IS NULL),
    CONSTRAINT fk_transaction_links_user FOREIGN KEY (user_id) REFERENCES app.users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_transaction_links_counterparty FOREIGN KEY (user_id, counterparty_account_id) REFERENCES app.accounts (user_id, id) ON DELETE RESTRICT
);

CREATE TABLE app.transaction_link_members (
    link_id           BIGINT NOT NULL,
    transaction_id    BIGINT NOT NULL,
    user_id           BIGINT NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_transaction_link_members PRIMARY KEY (link_id, transaction_id),
    CONSTRAINT ux_transaction_link_members_transaction UNIQUE (transaction_id),
    CONSTRAINT fk_link_members_user FOREIGN KEY (user_id) REFERENCES app.users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_link_members_link FOREIGN KEY (user_id, link_id) REFERENCES app.transaction_links (user_id, id) ON DELETE CASCADE,
    -- RESTRICT, not CASCADE: a linked transaction is deletable only once the service layer has
    -- moved or dissolved its link (§7.5) — this is what stops a delete from orphaning it silently.
    CONSTRAINT fk_link_members_transaction FOREIGN KEY (user_id, transaction_id) REFERENCES app.transactions (user_id, id) ON DELETE RESTRICT
);

CREATE TABLE app.dismissed_matches (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT NOT NULL,
    match_type          TEXT NOT NULL,
    transaction_id_a    BIGINT NOT NULL,
    transaction_id_b    BIGINT NOT NULL,
    dismissed_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_dismissed_matches PRIMARY KEY (id),
    CONSTRAINT ux_dismissed_matches_pair UNIQUE (user_id, match_type, transaction_id_a, transaction_id_b),
    CONSTRAINT chk_dismissed_matches_type CHECK (match_type IN ('TRANSFER', 'MERGE')),
    CONSTRAINT chk_dismissed_matches_order CHECK (transaction_id_a < transaction_id_b),
    CONSTRAINT fk_dismissed_matches_user FOREIGN KEY (user_id) REFERENCES app.users (id) ON DELETE RESTRICT,
    -- CASCADE (§7.3): a dismissal naming a deleted transaction is meaningless.
    CONSTRAINT fk_dismissed_matches_txn_a FOREIGN KEY (user_id, transaction_id_a) REFERENCES app.transactions (user_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_dismissed_matches_txn_b FOREIGN KEY (user_id, transaction_id_b) REFERENCES app.transactions (user_id, id) ON DELETE CASCADE
);

CREATE TABLE app.balance_checkpoints (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id                 BIGINT NOT NULL,
    account_id              BIGINT NOT NULL,
    as_of_date              DATE NOT NULL,
    actual_balance_paise    BIGINT NOT NULL,
    note                    TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_balance_checkpoints PRIMARY KEY (id),
    CONSTRAINT ux_balance_checkpoints_account_date UNIQUE (user_id, account_id, as_of_date),
    CONSTRAINT fk_balance_checkpoints_user FOREIGN KEY (user_id) REFERENCES app.users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_balance_checkpoints_account FOREIGN KEY (user_id, account_id) REFERENCES app.accounts (user_id, id) ON DELETE RESTRICT
);

CREATE INDEX ix_transactions_user_txn_date
    ON app.transactions (user_id, txn_date);

CREATE INDEX ix_transactions_account_txn_date_id
    ON app.transactions (account_id, txn_date, id);

CREATE INDEX ix_transactions_statement_import_id
    ON app.transactions (statement_import_id)
    WHERE statement_import_id IS NOT NULL;

CREATE UNIQUE INDEX ux_statement_imports_cc_statement
    ON app.statement_imports (user_id, account_id, statement_date)
    WHERE status = 'COMMITTED' AND statement_date IS NOT NULL;

-- No index for the §4.1 near-miss lookup (§9): ~2,000 rows/year makes the scan instant, so an
-- index would only cost write time on every import.
