spring:
  application:
    name: backend-local
  datasource:
    url: jdbc:postgresql://localhost:5432/financetracker
    username: financetracker
    password: financetracker_dev

management:
  endpoint:
    health:
      show-details: always
